#!/bin/sh
# LeroiAir $1{.cfl | .inv}
#
# Shell script to run $1 takes a single arguement which is the name of the 
# cfl.  If the program is used in inversion mode, then the .inv file must 
# have the same name as the .cfl

# make a job directory ...
clear
mkdir -p "$1"
cd "$1"

# copy command line arguments to job directory ...
test -f ../"$1".cfl && cp ../"$1".cfl LeroiAir.cfl
test -f ../"$1".inv && cp ../"$1".inv LeroiAir.inv

# run the program ...
LeroiAir.x

# copy output back to parent directory ...
test -f LeroiAir.out && cp LeroiAir.out ../"$1".out
test -f LeroiAir.mv1 && cp LeroiAir.mv1 ../"$1".mv1
test -f LeroiAir.mf1 && cp LeroiAir.mf1 ../"$1".mf1
test -f LeroiAir.amx && cp LeroiAir.amx ../"$1".amx
test -f LeroiAir.frq && cp LeroiAir.frq ../"$1".frq
test -f LeroiAir.log && cp LeroiAir.log ../"$1".log
test -f LeroiAir.flayer && cp LeroiAir.flayer ../"$1".flayer
test -f LeroiAir.wave && cp LeroiAir.wave ../"$1".wave
test -f LeroiAir.trp && cp LeroiAir.trp ../"$1".trp

# ... and kill the job directory
cd ..
rm -rf "$1"
