#!/bin/sh
# Samaya $1{.cfl | .inv}
#
# Shell script to run $1 takes a single arguement which is the name of the 
# cfl.  If the program is used in inversion mode, then the .inv file must 
# have the same name as the .cfl

# make a job directory ...
clear
mkdir -p "$1"
cd "$1"

# copy command line arguments to job directory ...
test -f ../"$1".cfl && cp ../"$1".cfl Samaya.cfl
test -f ../"$1".inv && cp ../"$1".inv Samaya.inv

# run the program ...
~/bin/Samaya.x

# copy output back to parent directory ...
test -f Samaya.out && cp Samaya.out ../"$1".out
test -f Samaya.mv1 && cp Samaya.mv1 ../"$1".mv1
test -f Samaya.mf1 && cp Samaya.mf1 ../"$1".mf1
test -f Samaya.amx && cp Samaya.amx ../"$1".amx
test -f Samaya.frq && cp Samaya.frq ../"$1".frq
test -f Samaya.log && cp Samaya.log ../"$1".log

# ... and kill the job directory
cd ..
rm -rf "$1"
