#!/bin/sh
# ArjunAir $1{.cfl | .inv}
#
# Shell script to run $1 takes a single arguement which is the name of the 
# cfl.  If the program is used in inversion mode, then the .inv file must 
# have the same name as the .cfl

# make a job directory ...
clear
mkdir -p "$1"
cd "$1"

# copy command line arguments to job directory ...
test -f ../"$1".cfl && cp ../"$1".cfl ArjunAir.cfl
test -f ../"$1".inv && cp ../"$1".inv ArjunAir.inv

# run the program ...
~/bin/ArjunAir.x

# copy output back to parent directory ...
test -f ArjunAir.out && cp ArjunAir.out ../"$1".out
test -f ArjunAir.mv1 && cp ArjunAir.mv1 ../"$1".mv1
test -f ArjunAir.mf1 && cp ArjunAir.mf1 ../"$1".mf1
test -f ArjunAir.frq && cp ArjunAir.frq ../"$1".frq
test -f ArjunAir.log && cp ArjunAir.log ../"$1".log

# ... and kill the job directory
cd ..
rm -rf "$1"