#!/bin/sh
# SamayaAir $1{.cfl | .inv}
#
# Shell script to run $1 takes a single arguement which is the name of the 
# cfl.  If the program is used in inversion mode, then the .inv file must 
# have the same name as the .cfl

# make a job directory ...
clear
mkdir -p "$1"
cd "$1"

# copy command line arguments to job directory ...
test -f ../"$1".cfl && cp ../"$1".cfl SamayaAir.cfl
test -f ../"$1".inv && cp ../"$1".inv SamayaAir.inv

# run the program ...
~/bin/SamayaAir.x

# copy output back to parent directory ...
test -f SamayaAir.out && cp SamayaAir.out ../"$1".out
test -f SamayaAir.mv1 && cp SamayaAir.mv1 ../"$1".mv1
test -f SamayaAir.mf1 && cp SamayaAir.mf1 ../"$1".mf1
test -f SamayaAir.amx && cp SamayaAir.amx ../"$1".amx
test -f SamayaAir.frq && cp SamayaAir.frq ../"$1".frq
test -f SamayaAir.log && cp SamayaAir.log ../"$1".log

# ... and kill the job directory
cd ..
rm -rf "$1"
