#!/bin/sh
# Leroi $1{.cfl | .inv}
#
# Shell script to run $1 takes a single arguement which is the name of the 
# cfl.  If the program is used in inversion mode, then the .inv file must 
# have the same name as the .cfl

# make a job directory ...
clear
mkdir -p "$1"
cd "$1"

# copy command line arguments to job directory ...
test -f ../"$1".cfl && cp ../"$1".cfl Leroi.cfl
test -f ../"$1".inv && cp ../"$1".inv Leroi.inv

# run the program ...
Leroi.x

# copy output back to parent directory ...
test -f Leroi.out && cp Leroi.out ../"$1".out
test -f Leroi.mv1 && cp Leroi.mv1 ../"$1".mv1
test -f Leroi.mf1 && cp Leroi.mf1 ../"$1".mf1
test -f Leroi.amx && cp Leroi.amx ../"$1".amx
test -f Leroi.frq && cp Leroi.frq ../"$1".frq
test -f Leroi.log && cp Leroi.log ../"$1".log
test -f Leroi.flayer && cp Leroi.flayer ../"$1".flayer
test -f Leroi.wave && cp Leroi.wave ../"$1".wave
test -f Leroi.trp && cp Leroi.trp ../"$1".trp

# ... and kill the job directory
cd ..
rm -rf "$1"
