#!/bin/sh

SamAir Dgm_P
SamAir Dgm_S
SamAir GTK_P
SamAir GTK_S
SamAir GtmX_B_P
SamAir GtmX_B_S
SamAir GtmX_dBdt_P
SamAir GtmX_dBdt_S
SamAir GtmXZ_B_P
SamAir GtmXZ_B_S
SamAir GtmXZ_dBdt_P
SamAir GtmXZ_dBdt_S
SamAir GtmZ_B_P
SamAir GtmZ_B_S
SamAir GtmZ_dBdt_P
SamAir GtmZ_dBdt_S
SamAir SpmX_P
SamAir SpmX_S
SamAir SpmXZ_P
SamAir SpmXZ_S
SamAir SpmZ_P
SamAir SpmZ_S
SamAir TmpX_P
SamAir TmpX_S
SamAir TmpXZ_P
SamAir TmpXZ_S
SamAir TmpZ_P
SamAir TmpZ_S
SamAir VTEM_P
SamAir VTEM_S